all: hw3_bits hw3_matmul hw3_struct_union_func

hw3_bits: hw3_bits.c
	gcc -g -Wall -O0 hw3_bits.c -o hw3_bits
	gcc -g -Wall -O0 -S hw3_bits.c -o hw3_bits.s

hw3_matmul: hw3_matmul.c
	gcc -g -Wall -O0 hw3_matmul.c -o hw3_matmul
	gcc -g -Wall -O0 -S hw3_matmul.c -o hw3_matmul.s

hw3_struct_union_func: hw3_struct_union_func.c
	gcc -g -Wall -O0 hw3_struct_union_func.c -o hw3_struct_union_func
	gcc -g -Wall -O0 -S hw3_struct_union_func.c -o hw3_struct_union_func.s

